// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaddleXserver.proto
// Original file comments:
// 二、加载模型要求：
// 模型目录中文件应该包括model.yml、__model__和__params__三个文件
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Example {
  public static class PaddleXserver
  {
    static readonly string __ServiceName = "example.PaddleXserver";

    static readonly Marshaller<global::Example.resquest_msg> __Marshaller_resquest_msg = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.resquest_msg.Parser.ParseFrom);
    static readonly Marshaller<global::Example.respone_msg> __Marshaller_respone_msg = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.respone_msg.Parser.ParseFrom);
    static readonly Marshaller<global::Example.paddlex_init_cmd> __Marshaller_paddlex_init_cmd = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.paddlex_init_cmd.Parser.ParseFrom);
    static readonly Marshaller<global::Example.paddlex_init_result> __Marshaller_paddlex_init_result = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.paddlex_init_result.Parser.ParseFrom);
    static readonly Marshaller<global::Example.image> __Marshaller_image = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.image.Parser.ParseFrom);
    static readonly Marshaller<global::Example.cls_inputs_result> __Marshaller_cls_inputs_result = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.cls_inputs_result.Parser.ParseFrom);
    static readonly Marshaller<global::Example.det_inputs_result> __Marshaller_det_inputs_result = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.det_inputs_result.Parser.ParseFrom);
    static readonly Marshaller<global::Example.det_seg_inputs_result> __Marshaller_det_seg_inputs_result = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.det_seg_inputs_result.Parser.ParseFrom);
    static readonly Marshaller<global::Example.seg_inputs_result> __Marshaller_seg_inputs_result = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.seg_inputs_result.Parser.ParseFrom);

    static readonly Method<global::Example.resquest_msg, global::Example.respone_msg> __Method_connect = new Method<global::Example.resquest_msg, global::Example.respone_msg>(
        MethodType.Unary,
        __ServiceName,
        "connect",
        __Marshaller_resquest_msg,
        __Marshaller_respone_msg);

    static readonly Method<global::Example.paddlex_init_cmd, global::Example.paddlex_init_result> __Method_paddlex_init = new Method<global::Example.paddlex_init_cmd, global::Example.paddlex_init_result>(
        MethodType.Unary,
        __ServiceName,
        "paddlex_init",
        __Marshaller_paddlex_init_cmd,
        __Marshaller_paddlex_init_result);

    static readonly Method<global::Example.image, global::Example.cls_inputs_result> __Method_paddlex_predict_cls = new Method<global::Example.image, global::Example.cls_inputs_result>(
        MethodType.Unary,
        __ServiceName,
        "paddlex_predict_cls",
        __Marshaller_image,
        __Marshaller_cls_inputs_result);

    static readonly Method<global::Example.image, global::Example.det_inputs_result> __Method_paddlex_predict_det = new Method<global::Example.image, global::Example.det_inputs_result>(
        MethodType.Unary,
        __ServiceName,
        "paddlex_predict_det",
        __Marshaller_image,
        __Marshaller_det_inputs_result);

    static readonly Method<global::Example.image, global::Example.det_seg_inputs_result> __Method_paddlex_predict_det_seg = new Method<global::Example.image, global::Example.det_seg_inputs_result>(
        MethodType.Unary,
        __ServiceName,
        "paddlex_predict_det_seg",
        __Marshaller_image,
        __Marshaller_det_seg_inputs_result);

    static readonly Method<global::Example.image, global::Example.seg_inputs_result> __Method_paddlex_predict_seg = new Method<global::Example.image, global::Example.seg_inputs_result>(
        MethodType.Unary,
        __ServiceName,
        "paddlex_predict_seg",
        __Marshaller_image,
        __Marshaller_seg_inputs_result);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Example.PaddleXserverReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PaddleXserver</summary>
    public abstract class PaddleXserverBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Example.respone_msg> connect(global::Example.resquest_msg request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Example.paddlex_init_result> paddlex_init(global::Example.paddlex_init_cmd request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Example.cls_inputs_result> paddlex_predict_cls(global::Example.image request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Example.det_inputs_result> paddlex_predict_det(global::Example.image request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Example.det_seg_inputs_result> paddlex_predict_det_seg(global::Example.image request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Example.seg_inputs_result> paddlex_predict_seg(global::Example.image request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PaddleXserver</summary>
    public class PaddleXserverClient : ClientBase<PaddleXserverClient>
    {
      /// <summary>Creates a new client for PaddleXserver</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PaddleXserverClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PaddleXserver that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PaddleXserverClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PaddleXserverClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PaddleXserverClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Example.respone_msg connect(global::Example.resquest_msg request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return connect(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Example.respone_msg connect(global::Example.resquest_msg request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_connect, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Example.respone_msg> connectAsync(global::Example.resquest_msg request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return connectAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Example.respone_msg> connectAsync(global::Example.resquest_msg request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_connect, null, options, request);
      }
      public virtual global::Example.paddlex_init_result paddlex_init(global::Example.paddlex_init_cmd request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return paddlex_init(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Example.paddlex_init_result paddlex_init(global::Example.paddlex_init_cmd request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_paddlex_init, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Example.paddlex_init_result> paddlex_initAsync(global::Example.paddlex_init_cmd request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return paddlex_initAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Example.paddlex_init_result> paddlex_initAsync(global::Example.paddlex_init_cmd request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_paddlex_init, null, options, request);
      }
      public virtual global::Example.cls_inputs_result paddlex_predict_cls(global::Example.image request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return paddlex_predict_cls(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Example.cls_inputs_result paddlex_predict_cls(global::Example.image request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_paddlex_predict_cls, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Example.cls_inputs_result> paddlex_predict_clsAsync(global::Example.image request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return paddlex_predict_clsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Example.cls_inputs_result> paddlex_predict_clsAsync(global::Example.image request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_paddlex_predict_cls, null, options, request);
      }
      public virtual global::Example.det_inputs_result paddlex_predict_det(global::Example.image request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return paddlex_predict_det(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Example.det_inputs_result paddlex_predict_det(global::Example.image request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_paddlex_predict_det, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Example.det_inputs_result> paddlex_predict_detAsync(global::Example.image request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return paddlex_predict_detAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Example.det_inputs_result> paddlex_predict_detAsync(global::Example.image request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_paddlex_predict_det, null, options, request);
      }
      public virtual global::Example.det_seg_inputs_result paddlex_predict_det_seg(global::Example.image request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return paddlex_predict_det_seg(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Example.det_seg_inputs_result paddlex_predict_det_seg(global::Example.image request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_paddlex_predict_det_seg, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Example.det_seg_inputs_result> paddlex_predict_det_segAsync(global::Example.image request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return paddlex_predict_det_segAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Example.det_seg_inputs_result> paddlex_predict_det_segAsync(global::Example.image request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_paddlex_predict_det_seg, null, options, request);
      }
      public virtual global::Example.seg_inputs_result paddlex_predict_seg(global::Example.image request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return paddlex_predict_seg(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Example.seg_inputs_result paddlex_predict_seg(global::Example.image request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_paddlex_predict_seg, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Example.seg_inputs_result> paddlex_predict_segAsync(global::Example.image request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return paddlex_predict_segAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Example.seg_inputs_result> paddlex_predict_segAsync(global::Example.image request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_paddlex_predict_seg, null, options, request);
      }
      protected override PaddleXserverClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PaddleXserverClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(PaddleXserverBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_connect, serviceImpl.connect)
          .AddMethod(__Method_paddlex_init, serviceImpl.paddlex_init)
          .AddMethod(__Method_paddlex_predict_cls, serviceImpl.paddlex_predict_cls)
          .AddMethod(__Method_paddlex_predict_det, serviceImpl.paddlex_predict_det)
          .AddMethod(__Method_paddlex_predict_det_seg, serviceImpl.paddlex_predict_det_seg)
          .AddMethod(__Method_paddlex_predict_seg, serviceImpl.paddlex_predict_seg).Build();
    }

  }
}
#endregion
