# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Set_Model_load(object):
    def setupUi(self, Set_Model_load):
        Set_Model_load.setObjectName("Set_Model_load")
        Set_Model_load.resize(300, 160)
        Set_Model_load.setMinimumSize(QtCore.QSize(300, 160))
        Set_Model_load.setMaximumSize(QtCore.QSize(300, 160))
        self.Load_Model_tip = QtWidgets.QLabel(Set_Model_load)
        self.Load_Model_tip.setGeometry(QtCore.QRect(40, 10, 221, 41))
        self.Load_Model_tip.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.Load_Model_tip.setAlignment(QtCore.Qt.AlignCenter)
        self.Load_Model_tip.setWordWrap(True)
        self.Load_Model_tip.setObjectName("Load_Model_tip")
        self.Bt_load_model = QtWidgets.QPushButton(Set_Model_load)
        self.Bt_load_model.setGeometry(QtCore.QRect(90, 70, 121, 31))
        self.Bt_load_model.setObjectName("Bt_load_model")
        self.finish_set = QtWidgets.QPushButton(Set_Model_load)
        self.finish_set.setGeometry(QtCore.QRect(90, 110, 101, 41))
        self.finish_set.setObjectName("finish_set")
        self.progressBar = QtWidgets.QProgressBar(Set_Model_load)
        self.progressBar.setGeometry(QtCore.QRect(70, 70, 151, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Bt_load_model.raise_()
        self.Load_Model_tip.raise_()
        self.finish_set.raise_()
        self.progressBar.raise_()

        self.retranslateUi(Set_Model_load)
        QtCore.QMetaObject.connectSlotsByName(Set_Model_load)

    def retranslateUi(self, Set_Model_load):
        _translate = QtCore.QCoreApplication.translate
        Set_Model_load.setWindowTitle(_translate("Set_Model_load", "Form"))
        self.Load_Model_tip.setText(_translate("Set_Model_load", "<html><head/><body><p>模型未加载，点击加载模型</p></body></html>"))
        self.Bt_load_model.setText(_translate("Set_Model_load", "加载模型"))
        self.finish_set.setText(_translate("Set_Model_load", "完成配置"))
