# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Set_Model_select(object):
    def setupUi(self, Set_Model_select):
        Set_Model_select.setObjectName("Set_Model_select")
        Set_Model_select.resize(320, 250)
        Set_Model_select.setMinimumSize(QtCore.QSize(320, 250))
        Set_Model_select.setMaximumSize(QtCore.QSize(320, 250))
        self.Select_Model_tip = QtWidgets.QLabel(Set_Model_select)
        self.Select_Model_tip.setGeometry(QtCore.QRect(50, 10, 161, 101))
        self.Select_Model_tip.setAlignment(QtCore.Qt.AlignCenter)
        self.Select_Model_tip.setWordWrap(True)
        self.Select_Model_tip.setObjectName("Select_Model_tip")
        self.Bt_select_model = QtWidgets.QPushButton(Set_Model_select)
        self.Bt_select_model.setGeometry(QtCore.QRect(20, 130, 101, 23))
        self.Bt_select_model.setObjectName("Bt_select_model")
        self.next_set = QtWidgets.QPushButton(Set_Model_select)
        self.next_set.setGeometry(QtCore.QRect(150, 190, 75, 23))
        self.next_set.setObjectName("next_set")
        self.model_dir = QtWidgets.QLabel(Set_Model_select)
        self.model_dir.setGeometry(QtCore.QRect(130, 120, 121, 41))
        self.model_dir.setStyleSheet("background-color: rgba(255, 85, 0, 100);")
        self.model_dir.setWordWrap(True)
        self.model_dir.setObjectName("model_dir")
        self.combobox_use_gpu = QtWidgets.QComboBox(Set_Model_select)
        self.combobox_use_gpu.setGeometry(QtCore.QRect(20, 190, 101, 21))
        self.combobox_use_gpu.setObjectName("combobox_use_gpu")
        self.combobox_use_gpu.addItem("")
        self.combobox_use_gpu.addItem("")

        self.retranslateUi(Set_Model_select)
        self.next_set.clicked.connect(Set_Model_select.close)
        QtCore.QMetaObject.connectSlotsByName(Set_Model_select)

    def retranslateUi(self, Set_Model_select):
        _translate = QtCore.QCoreApplication.translate
        Set_Model_select.setWindowTitle(_translate("Set_Model_select", "Form"))
        self.Select_Model_tip.setText(_translate("Set_Model_select", "<html><head/><body><p>请选择图片的</p><p>目标检测、实例分割、</p><p>图像分类、语义分割等模型</p></body></html>"))
        self.Bt_select_model.setText(_translate("Set_Model_select", "选择模型"))
        self.next_set.setText(_translate("Set_Model_select", "下一步"))
        self.model_dir.setText(_translate("Set_Model_select", "未选择模型"))
        self.combobox_use_gpu.setItemText(0, _translate("Set_Model_select", "使用CPU(默认)"))
        self.combobox_use_gpu.setItemText(1, _translate("Set_Model_select", "使用GPU"))
