# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Waring.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Waring(object):
    def setupUi(self, Waring):
        Waring.setObjectName("Waring")
        Waring.resize(320, 200)
        Waring.setMinimumSize(QtCore.QSize(320, 200))
        Waring.setMaximumSize(QtCore.QSize(320, 200))
        Waring.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButton = QtWidgets.QPushButton(Waring)
        self.pushButton.setGeometry(QtCore.QRect(120, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Waring)
        self.label.setGeometry(QtCore.QRect(0, 0, 321, 171))
        self.label.setStyleSheet("background-color: rgb(231, 255, 226);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Waring)
        self.pushButton.clicked.connect(Waring.close)
        QtCore.QMetaObject.connectSlotsByName(Waring)

    def retranslateUi(self, Waring):
        _translate = QtCore.QCoreApplication.translate
        Waring.setWindowTitle(_translate("Waring", "提示"))
        self.pushButton.setText(_translate("Waring", "确认"))
        self.label.setText(_translate("Waring", "无效的提示"))
